version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env # Loads POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD
    restart: always

  app:
    image: ghcr.io/thekoma/gpodder-docker:latest
    restart: always
    env_file:
      - .env # Loads MYGPO_SECRET_KEY, MYGPO_ALLOWED_HOSTS, MYGPO_DEFAULT_BASE_URL etc.
    environment:
      # Construct DATABASE_URL from variables loaded via env_file
      # Note: Ensure POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB are set in .env
      DATABASE_URL: postgresql://${POSTGRES_USER:-mygpo}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-mygpo}
      # Set other non-sensitive defaults or overrides if needed
      DEBUG: 'False'
      PORT: '8000' # Ensure this matches the EXPOSE in Dockerfile and CMD
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
